language: c

cache:
    apt: true
    ccache: true

before_script:
    - sudo apt-get -y install libevent-dev cmake
    - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-3.2.0/msgpack-3.2.0.tar.gz
    - tar xzf msgpack-3.2.0.tar.gz
    - cd msgpack-3.2.0
    - cmake CMakeLists.txt
    - make
    - sudo make install
    - cd ..
      
script:
    - ./configure
    - make

after_script: 
    - cd example 
    - make 
    - ./yar_server -S 127.0.0.1:9999
    - ./yar_client -h 127.0.0.1:9999
