git:
  quiet: true

dist: xenial
language: c
sudo: required
addons:
  apt:
    packages:
      - cmake
      - libevent-dev


cache:
    apt: true

before_script:
    - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-3.2.0/msgpack-3.2.0.tar.gz
    - tar xzf msgpack-3.2.0.tar.gz
    - cd msgpack-3.2.0
    - cmake CMakeLists.txt
    - make
    - sudo make install
    - cd ..
    - pecl install msgpack
    - echo yes | pecl install yar

script:
    - ./configure
    - make

after_script: 
    - cd example 
    - make 
    - ./yar_server -S 127.0.0.1:9999
    - ./yar_client -h 127.0.0.1:9999 && php -dyar.packager=msgpack client.php 127.0.0.1:9999
